name: Christian

summary:
  - Multidisciplinary engineer with expertise in geothermal energy, process engineering, and data science. Passionate about decarbonization, automation, and using data to optimize energy systems.
  - Experienced Data & Analytics Engineer with 4+ years in data engineering, science, and analytics. Currently at Climeworks, specializing in building BI platforms, developing ETL/ELT pipelines, and leveraging machine learning to optimize process operations. Passionate about using data-driven insights to enhance operational efficiency and inform strategic decisions.
  - Versatile Engineer with a broad range of experience, specializing in Renewable Energy. M.Sc. in Mechanical Engineering. Competencies include data analytics, programming, mass transport phenomena, and process optimization. Currently operating and troubleshooting world’s first/world’s largest Direct Air Capture (DAC) plant at Hellisheiði, Iceland. Eager to contribute to technology development, leveraging operational expertise and practical knowledge to optimize green-tech processes.
  - Versatile Process Engineer with hands-on experience operating pilot-scale Direct Air Capture (DAC) systems. Currently based in Iceland, operating and troubleshooting the world’s largest DAC pilot plant (Mammoth) at Hellisheiði. Holds an M.Sc. in Mechanical Engineering with a focus on renewable energy systems. Skilled in executing experimental procedures, process optimization, and integrating data analytics and programming into plant operations. Motivated to support breakthrough innovation in electrochemical DAC for permanent CO₂ removal.  


experience:
  - title: Operations Engineer - Process
    company: Climeworks
    location: Hellisheiði, Iceland
    start_date: 2023-11
    end_date: Present
    domain: [operations, engineering, process_engineering, data_engineering, data_science]
    description:
      - Ensured 24/7 plant operations through Mammoth expertise, maintaining smooth and efficient performance across all systems in a complex chemical environment.
      - Supported commissioning and start-up phases, contributing to the successful rollout of Mammoth and SOP documentation creation.
      - Collaborated with the data team using Databricks, Python, and Grafana to execute data science projects and enhance dashboards, improving data visibility and system performance.
      - Developed and applied machine learning models, using both linear and polynomial regression, to forecast CO₂ quality from ambient weather conditions.
      - Built and deployed an unsupervised anomaly detection pipeline (GMM, Isolation Forest) for identifying vacuum leaks, improving predictive maintenance and plant efficiency.
      - Facilitated root cause analysis and data analytics initiatives at Mammoth, driving performance improvements in a complex chemical process environment.
      - Developed Seeq dashboards to pinpoint underperforming chambers, enabling teams to focus on root causes and improve operations.
      - Resolved a critical issue within an hour after plant start-up, restoring operations after 24 hours of poor production and minimizing further downtime.
    skills: [Python, SQL, Databricks, Grafana, Machine Learning, Process Optimization, CO2 Capture, Vacuum Systems]

  - title: Data Engineer
    company: Gallup Iceland / Já.is
    location: Reykjavík, Iceland
    start_date: 2022-05
    end_date: 2023-10
    domain: [data_engineering, e-commerce]
    description:
      - Engineered high-performance ETL/ELT data pipelines (SQL, Python, AWS, Docker, Airflow) with technical teams to enhance cloud-based services.
      - Reduced Snowflake data warehouse costs by 30% through optimization strategies, including query performance tuning and efficient data storage practices.
      - Led the migration from Redshift to Snowflake, saving an estimated $1,400 per month.
      - Optimized a critical customer-facing query, reducing execution time from 3 minutes to 5 seconds.
      - Enhanced analytics for 100+ customers by integrating and cleansing diverse data sources through APIs and dbt workflows.
    skills: [SQL, Python, AWS, Airflow, Docker, Snowflake, Redshift, dbt]

  - title: SQL Developer
    company: Paradigm Manufacturing, Inc.
    location: Austin, Texas
    start_date: 2020-02
    end_date: 2023-10
    domain: [data_engineering]
    description:
      - Developed and optimized Python & SQL-based ETL solutions for the manufacturing sector, integrating APIs to automate data reporting and streamline processes.
      - Created and maintained a critical shipping report for over 60 users, improving logistics efficiency.
      - Built foundational coding infrastructure used by the software team, establishing robust standards and supporting scalability.
      - Delivered real-time SQL data to Excel for live updates on the manufacturing floor.
    skills: [SQL, Python, ETL, API Integration, Excel Automation]

  - title: IT Operations Engineer
    company: General Motors
    location: Austin, Texas
    start_date: 2016-07
    end_date: 2018-07
    domain: [operations, it]
    description:
      - Identified, evaluated, and prioritized systemic risks within a critical powertrain application used across 32 global manufacturing sites.
      - Closed 22% of team tickets, significantly improving team responsiveness.
      - Initiated and facilitated collaboration between GM and the University of Texas programming club.
    skills: [Risk Analysis, IT Operations, Collaboration, Incident Management]


education:
  - degree: M.Sc. in Renewable Energy Mechanical Engineering (Geothermal Engineering)
    institution: University of Iceland
    location: Reykjavik, Iceland
    graduation_year: 2023
    thesis: >
      Conversion of diesel-powered boilers for district heating to sustainable fuels.
      Analyzed thermal output and feasibility of biofuels and eFuels, providing recommendations to transition while maintaining system efficiency.
      This included modeling hydrogen-based e-fuel systems and performing techno-economic assessments to support decarbonization of hard-to-abate sectors.
    relevant_coursework:
      - Big Data and Cloud Computing
      - Computational Fluid Dynamics
      - Thermodynamics
      - Renewable Energy Systems
      - Corrosion
      - Power Plants

  - degree: B.Sc. in Petroleum Engineering
    institution: The University of Texas at Austin
    location: Austin, Texas
    graduation_year: 2016
    relevant_coursework:
      - Transport Phenomena
      - Thermodynamics
      - Physical Chemistry
      - Mechanics of Solids
      - Properties of Fluids 1 & 2
      - Reservoir Simulation
      - Vector Calculus
      - Differential Equations

skills:
  data_engineering:
    - SQL
    - Databricks
    - Airflow
    - Docker
    - ECS
    - Snowflake

  data_science:
    - Pandas
    - Scikit-learn
    - MLflow
    - KMeans
    - Unsupervised Learning
    - Anomaly Detection

  process_engineering:
    - PID Control
    - Root Cause Analysis
    - Geothermal Systems
    - Carbon Capture
    - Heat Exchangers
    - Steam and Vacuum Dynamics

narrative_blurbs:
  data_engineering: >
    I love building pipelines that transform messy industrial data into clean, usable formats.
    Data engineering bridges my technical curiosity with a love for system design.

  data_science: >
    My goal is to uncover trends and anomalies that lead to real operational improvements.
    I enjoy designing models that are not only accurate but interpretable and useful.

  process_engineering: >
    Nothing beats understanding a process from the ground up — from thermodynamics to sensor noise.
    I thrive at the intersection of field operations and control systems.

projects:
  work:
    - name: Vacuum Leak Detector
      year: 2025
      description: >
        Designed an unsupervised machine learning model to detect vacuum leaks in a geothermal-powered
        carbon capture plant, using control valve behavior, hot feed water temperature, and pressure sensor data.

  personal:
    - name: Smart Resume Generator
      year: 2025
      description: >
        Built a Python tool to analyze job descriptions and generate tailored CVs using keyword extraction,
        bigram/trigram analysis, and customizable LaTeX templates.

languages:
  - English (native)
  - German (beginner)
  - Icelandic (beginner)
  - Spanish (intermediate)